version: "3.9"

services:
  novelgen:
    build: .
    container_name: NovelGen

    volumes:
      - .:/app
      - ./outputs:/app/outputs
      - ./manuscripts:/app/manuscripts

    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

    command: python src/main.py